// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageMesh.Server.Data;

#nullable disable

namespace StorageMesh.Server.Migrations
{
    [DbContext(typeof(StorageMeshDbContext))]
    [Migration("20260926003444_AddNodeEvents")]
    partial class AddNodeEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("StorageMesh.Server.Models.LocalFile", b =>
                {
                    b.Property<string>("FileKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FileKey");

                    b.ToTable("LocalFiles");
                });

            modelBuilder.Entity("StorageMesh.Server.Models.NodeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NodeEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
