// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageMesh.Server.Data;

#nullable disable

namespace StorageMesh.Server.Migrations
{
    [DbContext(typeof(StorageMeshDbContext))]
    partial class StorageMeshDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("StorageMesh.Server.Models.LocalFile", b =>
                {
                    b.Property<string>("FileKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FileKey");

                    b.ToTable("LocalFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
