FROM node:22 AS client-build

WORKDIR /app/storagemesh.client

COPY storagemesh.client/package*.json ./

RUN npm install

COPY storagemesh.client/ ./

RUN npm run build

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS server-build

WORKDIR /app

COPY StorageMesh.Server/StorageMesh.Server.csproj StorageMesh.Server/

RUN dotnet restore StorageMesh.Server/StorageMesh.Server.csproj

COPY StorageMesh.Server/ StorageMesh.Server/

COPY --from=client-build \
    /app/storagemesh.client/dist \
    /app/StorageMesh.Server/wwwroot

WORKDIR /app/StorageMesh.Server

RUN dotnet publish \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app

COPY --from=server-build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "StorageMesh.Server.dll"]