services:

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storagemesh-node1
    volumes:
      - ./config/node1.json:/app/node.json:ro

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storagemesh-node2
    volumes:
      - ./config/node2.json:/app/node.json:ro

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storagemesh-node3
    volumes:
      - ./config/node3.json:/app/node.json:ro

  node4:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: storagemesh-node4
    ports:
      - "8080:8080"
    volumes:
      - ./config/node4.json:/app/node.json:ro
    depends_on:
      - node1
      - node2
      - node3